### ISSUE TITLE
Unable to open file for reading [filename] yii2 swiftmailer

### ISSUE THREAD

**Issue by gojiraKi** [yiisoft/yii2-swiftmailer#87]
### What steps will reproduce the problem?
Embedding image to mail with swiftmailer in Yii2

### What's expected?
Able to embed image

### What do you get instead?
Unable to open file for reading [filename] yii2 swiftmailer

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.14
| Yii SwiftMailer version | 2.1.0 (Most of my previous installation of Yii2 has also this issue)
| SwiftMailer version     | 6.2.7
| PHP version             | 7.2.5
| Operating system        | Windows 10

**Comment by gojiraKi** [comment]
Hi,
This is my first time reporting a bug. On the file located at 
`\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php`
on line number 129, the statement
`$pointer = @fopen($this->path, 'rb');`
has an extra `@` in front of the function `fopen` which is causing this issue. Removing the extra `@` solved the issue.
So the correct statement should be
`$pointer = fopen($this->path, 'rb')`;
I checked my previous installation of Yii2 application and most of them have this error.

**Comment by bizley** [comment]
There are few things here.
1. You are pointing at the code in Swiftmailer library but you open the issue at Yii repository which only uses Swiftmailer as dependency.
2. `@` is there to prevent output of notices and errors since Swiftmailer is only interested in the result of `fopen` so I don't know how removing it could fix the problem while having it causes the problem.
